language: java
jdk:
- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
  before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

