language: java
script: "mvn cobertura:cobertura"
jdk:
- oraclejdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
#- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://codecov.io/bash) -t 9ffa0785-687c-4b20-80dc-14e5465f460a
 install:       #true
- mvn -N io.takari:maven:wrapper
  before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

